networks:
  born:
    driver: bridge
services:
  nginx:
    build:
      args:
        NGINX_VERSION: ${NGINX_VERSION}
        TZ: ${TZ}
      context: nginx
    networks:
    - born
    ports:
    - 32782:80
    volumes:
    - ./logs/nginx/:/var/log/nginx
    - ../:/app
  php:
    build:
      args:
        PHP_VERSION: ${PHP_VERSION}
        TZ: ${TZ}
      context: php
    networks:
    - born
    tty: 'true'
    volumes:
    - ../:/app:rw
version: '3.7'
